services:
  redis:
    image: redis:latest
    container_name: prompt_server_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - prompt_network

  manim:
    image: manimcommunity/manim
    container_name: my-manim-container
    volumes:
      - "/Users/dinesh/Desktop/Web Projects/Prompt To Motion/python-worker:/manim"
    working_dir: /manim
    stdin_open: true
    tty: true
    command: bash
    networks:
      - prompt_network

volumes:
  redis_data:
    driver: local

networks:
  prompt_network:
    driver: bridge